import * as React from 'react'
import {
  Body,
  Container,
  Head,
  Heading,
  Hr,
  Html,
  Link,
  Preview,
  Row,
  Column,
  Section,
  Text,
} from '@react-email/components'
import type { TemplateEntry } from './registry'

interface InvoiceLink {
  name: string
  url: string
}
interface Entry {
  date: string
  direction: 'in' | 'out'
  amount: number
  description: string
  category?: string | null
  invoices: InvoiceLink[]
}
interface MissingItem {
  date: string
  direction: 'in' | 'out'
  amount: number
  description: string
}
interface Props {
  appUrl?: string
  companyName?: string
  currency?: string
  periodLabel?: string
  startIso?: string
  endIso?: string
  totals?: { received: number; spent: number; net: number; count: number; missingCount: number }
  entries?: Entry[]
  missing?: MissingItem[]
}

const fmt = (n: number, currency = 'EUR') =>
  new Intl.NumberFormat('en-IE', { style: 'currency', currency, maximumFractionDigits: 2 }).format(n)

const HandoffLedger = ({
  appUrl = 'https://bynku.app',
  companyName = 'Company',
  currency = 'EUR',
  periodLabel = '',
  startIso = '',
  endIso = '',
  totals = { received: 0, spent: 0, net: 0, count: 0, missingCount: 0 },
  entries = [],
  missing = [],
}: Props) => {
  return (
    <Html lang="en" dir="ltr">
      <Head />
      <Preview>
        {companyName} — bookkeeping handoff for {periodLabel} ({totals.count} entries)
      </Preview>
      <Body style={main}>
        <Container style={container}>
          <Heading style={h1}>Bookkeeping handoff</Heading>
          <Text style={muted}>
            {companyName} · {periodLabel} · {startIso} → {endIso}
          </Text>

          <Section style={statCard}>
            <Row>
              <Column style={statCol}>
                <Text style={statLabel}>Received</Text>
                <Text style={statValue}>{fmt(totals.received, currency)}</Text>
              </Column>
              <Column style={statCol}>
                <Text style={statLabel}>Paid</Text>
                <Text style={statValue}>{fmt(totals.spent, currency)}</Text>
              </Column>
              <Column style={statCol}>
                <Text style={statLabel}>Net</Text>
                <Text style={statValue}>{fmt(totals.net, currency)}</Text>
              </Column>
            </Row>
            <Hr style={hr} />
            <Text style={smallMuted}>
              {totals.count} entries · {totals.missingCount} without an invoice
            </Text>
          </Section>

          {missing.length > 0 && (
            <Section style={warnBox}>
              <Text style={warnTitle}>
                ⚠ {missing.length} entr{missing.length === 1 ? 'y is' : 'ies are'} missing an invoice
              </Text>
              {missing.slice(0, 40).map((m, i) => (
                <Text key={`m-${i}`} style={warnRow}>
                  {m.date} · {m.direction === 'in' ? 'Received' : 'Paid'} {fmt(m.amount, currency)} ·{' '}
                  {m.description}
                </Text>
              ))}
              {missing.length > 40 && <Text style={warnRow}>…and {missing.length - 40} more.</Text>}
            </Section>
          )}

          <Heading as="h3" style={h3}>
            Ledger
          </Heading>
          <Row style={theadRow}>
            <Column style={{ ...thDate }}>Date</Column>
            <Column style={{ ...thDesc }}>Description</Column>
            <Column style={{ ...thAmount }}>Amount</Column>
            <Column style={{ ...thInv }}>Invoice</Column>
          </Row>
          {entries.map((e, i) => (
            <Row key={`e-${i}`} style={tr}>
              <Column style={tdDate}>{e.date}</Column>
              <Column style={tdDesc}>{e.description}</Column>
              <Column
                style={{ ...tdAmount, color: e.direction === 'in' ? '#166534' : '#0f172a' }}
              >
                {e.direction === 'in' ? '+' : '−'}
                {fmt(e.amount, currency)}
              </Column>
              <Column style={tdInv}>
                {e.invoices.length > 0 ? (
                  e.invoices.map((inv, j) => (
                    <Link key={`i-${j}`} href={inv.url} style={invLink}>
                      {inv.name}
                    </Link>
                  ))
                ) : (
                  <span style={missingTag}>missing</span>
                )}
              </Column>
            </Row>
          ))}

          <Text style={footer}>
            Generated by {''}
            <Link href={appUrl} style={link}>
              bynku
            </Link>
            . Invoice links stay valid for 14 days. Amounts are as recorded by the business.
          </Text>
        </Container>
      </Body>
    </Html>
  )
}

export default HandoffLedger

export const template = {
  component: HandoffLedger,
  subject: (data: Record<string, any>) =>
    `Bookkeeping handoff — ${data?.companyName ?? 'Company'} ${data?.periodLabel ?? ''}`.trim(),
  displayName: 'Accountant handoff',
  previewData: {
    appUrl: 'https://bynku.app',
    companyName: 'Solenix Engineering',
    currency: 'EUR',
    periodLabel: 'Q3 2026',
    startIso: '2026-07-01',
    endIso: '2026-09-30',
    totals: { received: 42000, spent: 18350.5, net: 23649.5, count: 3, missingCount: 1 },
    entries: [
      {
        date: '2026-07-04',
        direction: 'in',
        amount: 12000,
        description: 'Client A — milestone 1',
        invoices: [{ name: 'inv-2026-014.pdf', url: 'https://bynku.app' }],
      },
      {
        date: '2026-07-18',
        direction: 'out',
        amount: 2350.5,
        description: 'Cloud hosting',
        invoices: [{ name: 'receipt.pdf', url: 'https://bynku.app' }],
      },
      { date: '2026-08-02', direction: 'out', amount: 900, description: 'Office supplies', invoices: [] },
    ],
    missing: [{ date: '2026-08-02', direction: 'out', amount: 900, description: 'Office supplies' }],
  },
} satisfies TemplateEntry

const main = { backgroundColor: '#ffffff', fontFamily: 'Arial, sans-serif' }
const container = { padding: '24px', maxWidth: '680px' }
const h1 = { fontSize: '22px', fontWeight: 'bold' as const, color: '#0f172a', margin: '0 0 4px' }
const h3 = { fontSize: '14px', fontWeight: 'bold' as const, color: '#0f172a', margin: '20px 0 8px' }
const muted = { fontSize: '12px', color: '#64748b', margin: '0 0 16px' }
const smallMuted = { fontSize: '11px', color: '#64748b', margin: '4px 0 0' }
const hr = { borderColor: '#e2e8f0', margin: '10px 0' }
const statCard = { border: '1px solid #e2e8f0', borderRadius: '12px', padding: '14px 16px', margin: '8px 0 16px' }
const statCol = { verticalAlign: 'top' as const, padding: '4px 6px' }
const statLabel = { fontSize: '11px', color: '#64748b', margin: 0, textTransform: 'uppercase' as const, letterSpacing: '0.05em' }
const statValue = { fontSize: '18px', fontWeight: 'bold' as const, color: '#0f172a', margin: '4px 0 2px' }
const warnBox = { border: '1px solid #fecaca', backgroundColor: '#fef2f2', borderRadius: '10px', padding: '12px 14px', margin: '0 0 16px' }
const warnTitle = { fontSize: '13px', fontWeight: 'bold' as const, color: '#b91c1c', margin: '0 0 6px' }
const warnRow = { fontSize: '12px', color: '#7f1d1d', margin: '2px 0' }
const theadRow = { borderBottom: '2px solid #e2e8f0', padding: '4px 0' }
const thDate = { fontSize: '11px', color: '#64748b', width: '90px', padding: '4px 6px', textTransform: 'uppercase' as const }
const thDesc = { fontSize: '11px', color: '#64748b', padding: '4px 6px', textTransform: 'uppercase' as const }
const thAmount = { fontSize: '11px', color: '#64748b', width: '110px', textAlign: 'right' as const, padding: '4px 6px', textTransform: 'uppercase' as const }
const thInv = { fontSize: '11px', color: '#64748b', width: '160px', padding: '4px 6px', textTransform: 'uppercase' as const }
const tr = { borderBottom: '1px solid #eef2f7' }
const tdDate = { fontSize: '12px', color: '#0f172a', width: '90px', padding: '6px' }
const tdDesc = { fontSize: '12px', color: '#0f172a', padding: '6px' }
const tdAmount = { fontSize: '12px', fontWeight: 'bold' as const, width: '110px', textAlign: 'right' as const, padding: '6px' }
const tdInv = { fontSize: '12px', width: '160px', padding: '6px' }
const invLink = { color: '#0f172a', textDecoration: 'underline', display: 'block' as const, fontSize: '12px' }
const missingTag = { color: '#b91c1c', fontSize: '11px', fontWeight: 'bold' as const }
const link = { color: '#0f172a', textDecoration: 'underline' }
const footer = { fontSize: '11px', color: '#94a3b8', margin: '20px 0 0', lineHeight: '1.5' }
