ALTER TABLE public.households
  ADD COLUMN IF NOT EXISTS country text NOT NULL DEFAULT 'PT',
  ADD COLUMN IF NOT EXISTS adults integer NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS children integer NOT NULL DEFAULT 0;